source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target '<%= @project %>' do

	# public repository
	pod 'HockeySDK-Source'

	pod 'RxSwift'
	# pod 'RxCocoa'
	# pod 'RxAlamofire'
    	pod 'RxAppState'
    	# pod 'RxKeyboard'
    
	pod 'SwiftyJSON' 
	pod 'Alamofire'
	pod 'ObjectMapper'

        #pod 'RealmSwift'
	#pod 'ObjectMapper+Realm'
    
	pod 'Socket.IO-Client-Swift'
	pod 'Kingfisher'

	pod 'IQKeyboardManagerSwift'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
    
    Dir.glob(installer.sandbox.target_support_files_root + "Pods-*/*.sh").each do |script|
        flag_name = File.basename(script, ".sh") + "-Installation-Flag"
        folder = "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"
        file = File.join(folder, flag_name)
        content = File.read(script)
        content.gsub!(/set -e/, "set -e\nKG_FILE=\"#{file}\"\nif [ -f \"$KG_FILE\" ]; then exit 0; fi\nmkdir -p \"#{folder}\"\ntouch \"$KG_FILE\"")
        File.write(script, content)
    end
end
