source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'giftadvice' do
  pod 'OwlKit', :git => 'https://github.com/malcommac/Owl.git', :branch => 'develop'
  pod 'PureLayout'
  pod 'PhoneNumberKit', '~> 2.6'
  pod 'RealmSwift'
	pod 'SwiftyJSON' 
	pod 'Alamofire'
	pod 'ObjectMapper'
    pod 'UITextView+Placeholder'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Clarifai'
    pod 'CameraManager'
    #pod 'ObjectMapper+Realm'
    pod 'pop'
    pod 'Kingfisher', '~> 5.0'
	pod 'IQKeyboardManagerSwift'
  pod 'RSKGrowingTextView'
end
